// Auto-generated by the postman-to-k6 converter

import "./libs/shim/core.js";

export let options = { maxRedirects: 4 };

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options
});

export default function() {
  postman[Request]({
    name: "Get Users",
    id: "cedcee67-ad5e-4282-908f-73773fe6ef5d",
    method: "GET",
    address: "https://jsonplaceholder.typicode.com/users"
  });

  postman[Request]({
    name: "Create User",
    id: "899e717b-8030-4b49-8b5c-efb416f38c9f",
    method: "POST",
    address: "https://jsonplaceholder.typicode.com/users",
    data: '{\n  "name": "John Doe",\n  "email": "john@example.com"\n}',
    headers: {
      "Content-Type": "application/json"
    }
  });

  postman[Request]({
    name: "Update User",
    id: "330063b7-b3de-44bb-981d-2287bd9cc604",
    method: "PUT",
    address: "https://jsonplaceholder.typicode.com/users/1",
    data: '{\n  "name": "Updated Name",\n  "email": "updated@example.com"\n}',
    headers: {
      "Content-Type": "application/json"
    }
  });
}
