// Auto-generated by the postman-to-k6 converter

import "./libs/shim/core.js";

export let options = { maxRedirects: 4 };

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options
});

export default function() {
  postman[Request]({
    name: "Get Users",
    id: "6c231953-2592-469e-bbc1-933bb5888b7f",
    method: "GET",
    address: "https://jsonplaceholder.typicode.com/users"
  });

  postman[Request]({
    name: "Create User",
    id: "969b25db-f40b-44df-b5f4-610edbc542b9",
    method: "POST",
    address: "https://jsonplaceholder.typicode.com/users",
    data: '{\n  "name": "John Doe",\n  "email": "john@example.com"\n}',
    headers: {
      "Content-Type": "application/json"
    }
  });

  postman[Request]({
    name: "Update User",
    id: "efe9ff88-edb7-44f5-9e93-86eca0e3d627",
    method: "PUT",
    address: "https://jsonplaceholder.typicode.com/users/1",
    data: '{\n  "name": "Updated Name",\n  "email": "updated@example.com"\n}',
    headers: {
      "Content-Type": "application/json"
    }
  });
}
