// Auto-generated by the postman-to-k6 converter

import "./libs/shim/core.js";

export let options = { maxRedirects: 4 };

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options
});

export default function() {
  postman[Request]({
    name: "Get Users",
    id: "81428a1e-0538-467e-91ff-34b2e55ba5cf",
    method: "GET",
    address: "https://jsonplaceholder.typicode.com/users"
  });

  postman[Request]({
    name: "Create User",
    id: "d4cae35f-9c35-44ee-9d4f-b5dd83184a84",
    method: "POST",
    address: "https://jsonplaceholder.typicode.com/users",
    data: '{\n  "name": "John Doe",\n  "email": "john@example.com"\n}',
    headers: {
      "Content-Type": "application/json"
    }
  });

  postman[Request]({
    name: "Update User",
    id: "76d4d093-2c8d-48bb-846a-7e7718cb3a89",
    method: "PUT",
    address: "https://jsonplaceholder.typicode.com/users/1",
    data: '{\n  "name": "Updated Name",\n  "email": "updated@example.com"\n}',
    headers: {
      "Content-Type": "application/json"
    }
  });
}
